"""Initial schema

Revision ID: 001_initial_schema
Revises: 
Create Date: 2026-08-21 14:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '001_initial_schema'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shows',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('section', sa.String(length=50), nullable=True),
    sa.Column('categories', sa.JSON(), nullable=False),
    sa.Column('synopsis', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('publish_runs',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('published_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('show_count', sa.Integer(), nullable=False),
    sa.Column('episode_count', sa.Integer(), nullable=False),
    sa.Column('catalogue_key', sa.String(length=500), nullable=True),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['published_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seasons',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('show_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('season_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('show_id', 'season_number', name='uix_show_season_number')
    )
    op.create_table('episodes',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('season_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('episode_number', sa.Integer(), nullable=False),
    sa.Column('episode_title', sa.String(length=255), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('content_group', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_group', 'language', name='uix_content_group_language')
    )
    op.create_index('idx_content_group', 'episodes', ['content_group'], unique=False)
    op.create_index('idx_season_id_episode_number', 'episodes', ['season_id', 'episode_number'], unique=False)
    op.create_table('artwork',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('episode_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('artwork_type', sa.String(length=20), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('episode_id', 'artwork_type', name='uix_episode_artwork_type')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artwork')
    op.drop_index('idx_season_id_episode_number', table_name='episodes')
    op.drop_index('idx_content_group', table_name='episodes')
    op.drop_table('episodes')
    op.drop_table('seasons')
    op.drop_table('publish_runs')
    op.drop_table('users')
    op.drop_table('shows')
    # ### end Alembic commands ###
